import "./style.css"
import { WebSocketMessage } from "./types";

// Setup Web Socket
const webSocketProtocol = window.location.protocol === "https:" ? "wss" : "ws";

let webSocketHost = window.location.host; // No matter the public url generated by ngrok, client can still connect to the server.
if (import.meta.env.MODE === "development") {
    console.log("Development environment. Setting host to localhost:3000");
    webSocketHost = "localhost:3000"; // Vite dev server hosts on localhost:5173
}

const socketURL = `${webSocketProtocol}://${webSocketHost}/`;
console.log("Creating socket on url:", socketURL);

let socket = new WebSocket(`${webSocketProtocol}://${webSocketHost}/`);

socket.onopen = () => {
    const message: WebSocketMessage = { origin: "web-controller", message: "connected" };
    socket.send(JSON.stringify(message));
};

socket.onmessage = (message) => {
    console.log("Received server message:", message.data);
};

// Setup buttons
const keyDownButton = document.getElementById("keydown-button");
const keyUpButton = document.getElementById("keyup-button");

if (!keyUpButton || !keyDownButton) {
    throw new Error();
}

keyDownButton.addEventListener("click", () => {
    const message: WebSocketMessage = { origin: "web-controller", message: "keydown-jump" };
    socket.send(JSON.stringify(message));
});

keyUpButton.addEventListener("click", () => {
    const message: WebSocketMessage = { origin: "web-controller", message: "keyup-jump" };
    socket.send(JSON.stringify(message));
});
